# Generated by Django 4.1 on 2023-08-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preforms',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shrinkwrapper',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='store',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cap',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Preforms',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='ShrinkWrapper',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
