# Generated by Django 4.1 on 2023-11-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sales',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
