# Generated by Django 4.1 on 2023-11-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_purchase_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
