# Generated by Django 4.1 on 2024-01-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_purchase_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='product',
        ),
    ]
